// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Installed Prisma 7.9 config type only supports `url` + `shadowDatabaseUrl`
    // (no `directUrl`), unlike some upgrade-guide examples. For Supabase, point
    // this at the DIRECT (non-pooled, port 5432) connection when running
    // migrations locally; the app's runtime client (src/shared/prisma.ts) reads
    // DATABASE_URL independently and can use the pooled URL in deployed envs.
    url: process.env["DATABASE_URL"],
  },
});
